export const USER_PERMISSIONS = {
  DELETE_LEADERBOARD_ITEMS: 'DELETE_LEADERBOARD_ITEMS',
  ADD_NEW_LEADERBOARD_ITEMS: 'ADD_NEW_LEADERBOARD_ITEMS',
  ENABLE_NEW_LEADERBOARD_UI: 'ENABLE_NEW_LEADERBOARD_UI',
  ENABLE_GOD_RIGHTS: 'ENABLE_GOD_RIGHTS',
  ENABLE_DECISION_MAKING: 'ENABLE_DECISION_MAKING',
}